<?php
declare(strict_types=1);

/**
 * AccountsApi.
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Click
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * DocuSign Click API
 *
 * Elastic signing (also known as DocuSign Click)  lets you capture consent to standard agreement terms with a single click: terms and conditions, terms of service, terms of use, privacy policies, and more. The Click API lets you include this customizable elastic template solution in your DocuSign integrations.
 *
 * OpenAPI spec version: v1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Click\Api\AccountsApi;

/**
 * GetClickwrapAgreementsOptions Class Doc Comment
 *
 * @category Class
 * @package  DocuSign\Click
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

class GetClickwrapAgreementsOptions
{
    /**
      * $client_user_id The client user ID to filter to a single user's agreements.
      * @var ?string
      */
    protected ?string $client_user_id = null;

    /**
     * Gets client_user_id
     *
     * @return ?string
     */
    public function getClientUserId(): ?string
    {
        return $this->client_user_id;
    }

    /**
     * Sets client_user_id
     * @param ?string $client_user_id The client user ID to filter to a single user's agreements.
     *
     * @return self
     */
    public function setClientUserId(?string $client_user_id): self
    {
        $this->client_user_id = $client_user_id;
        return $this;
    }
    /**
      * $from_date The earliest date to return agreements from.
      * @var ?string
      */
    protected ?string $from_date = null;

    /**
     * Gets from_date
     *
     * @return ?string
     */
    public function getFromDate(): ?string
    {
        return $this->from_date;
    }

    /**
     * Sets from_date
     * @param ?string $from_date The earliest date to return agreements from.
     *
     * @return self
     */
    public function setFromDate(?string $from_date): self
    {
        $this->from_date = $from_date;
        return $this;
    }
    /**
      * $page_number The results for this endpoint are paginated. Use this parameter to indicate which page to return. The `minimumPagesRemaining` value in the response indicates whether to continue querying for additional pages.  For example, if the page size is 40: * If this property is set to 0 (the default), the endpoint returns results 1-40. * If this property is set to 1, the endpoint returns results 41-80.  The default value is 0.
      * @var ?string
      */
    protected ?string $page_number = null;

    /**
     * Gets page_number
     *
     * @return ?string
     */
    public function getPageNumber(): ?string
    {
        return $this->page_number;
    }

    /**
     * Sets page_number
     * @param ?string $page_number The results for this endpoint are paginated. Use this parameter to indicate which page to return. The `minimumPagesRemaining` value in the response indicates whether to continue querying for additional pages.  For example, if the page size is 40: * If this property is set to 0 (the default), the endpoint returns results 1-40. * If this property is set to 1, the endpoint returns results 41-80.  The default value is 0.
     *
     * @return self
     */
    public function setPageNumber(?string $page_number): self
    {
        $this->page_number = $page_number;
        return $this;
    }
    /**
      * $status User agreement status. One of:  - `created` - `agreed` - `declined`
      * @var ?string
      */
    protected ?string $status = null;

    /**
     * Gets status
     *
     * @return ?string
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets status
     * @param ?string $status User agreement status. One of:  - `created` - `agreed` - `declined`
     *
     * @return self
     */
    public function setStatus(?string $status): self
    {
        $this->status = $status;
        return $this;
    }
    /**
      * $to_date The latest date to return agreements from.
      * @var ?string
      */
    protected ?string $to_date = null;

    /**
     * Gets to_date
     *
     * @return ?string
     */
    public function getToDate(): ?string
    {
        return $this->to_date;
    }

    /**
     * Sets to_date
     * @param ?string $to_date The latest date to return agreements from.
     *
     * @return self
     */
    public function setToDate(?string $to_date): self
    {
        $this->to_date = $to_date;
        return $this;
    }
}